Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"  # Updated to newer version
  
  config.vm.define "afadlaneS" do |master|
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.network "forwarded_port", guest: 80, host: 8080 , host_ip: "0.0.0.0"
    master.vm.synced_folder "./confs", "/vagrant", type: "virtualbox"
    master.vm.hostname = "afadlaneS"
    
    master.vm.provider "virtualbox" do |vb|
      vb.memory = 2048 
      vb.cpus = 1        
      vb.name = "afadlaneS"
    end

    master.vm.provision "shell", path: "scripts/script.sh"

  end
end